[theme]
base = "dark"
primaryColor = "#ff9d00"
backgroundColor = "#05080f"
secondaryBackgroundColor = "#0f1726"
textColor = "#f5f7fb"
font = "sans serif"

[server]
maxUploadSize = 500

[browser]
gatherUsageStats = false
