[theme]
base = "light"
primaryColor = "#16354a"
backgroundColor = "#f7f8fa"
secondaryBackgroundColor = "#edf1f5"
textColor = "#172a3a"
font = "sans serif"

[server]
maxUploadSize = 500

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
